### ISSUE TITLE
[MINOR] issue: The show recommendation button on the survey page does not do anything

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/h-team#45]
On the survey page, there is a big show recommendation button. After finishing 5-6 questions, I expect for it to show recommended place when clicking it, however, it does not return anything while clicked.

**Comment by mariamk-2740** [comment]
Link to duplicate issues, refer to for more details:
https://github.com/info442-spr22/h-team/issues/45

https://github.com/info442-spr22/h-team/issues/59

https://github.com/info442-spr22/h-team/issues/57

https://github.com/info442-spr22/h-team/issues/53

https://github.com/info442-spr22/h-team/issues/52

https://github.com/info442-spr22/h-team/issues/50

https://github.com/info442-spr22/h-team/issues/47

**Comment by mariamk-2740** [comment]
We will address this issue during this sprint.

**Comment by LouisXO** [comment]
Problem fixed with the commit [``](https://github.com/info442-spr22/h-team/tree/216d075396f389da786a9c55471db3e5f10d52a2)

**Comment by LouisXO** [comment]
Issue Fixed with commit [Link](https://github.com/info442-spr22/h-team/tree/216d075396f389da786a9c55471db3e5f10d52a2)
