### ISSUE TITLE
(minor bug) Pressing "show recommendations" button before finishing quiz restarts the quiz

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/h-team#46]
Pressing "show recommendations" should show islands to go to, but this only works after going through every page of the quiz. 
(Chrome Version 101.0.4951.64)
It would be helpful to remove the button until the very last question or add a note somewhere on the quiz to complete every question before pressing the button.

**Comment by mariamk-2740** [comment]
We will address this issue during this sprint.

**Comment by mariamk-2740** [comment]
https://github.com/info442-spr22/h-team/issues/54
^Duplicate link

**Comment by hannanajmal** [comment]
Thank you for giving us this suggestion. We will have the show recommendations button display at the end of the survey instead of on every single page

**Comment by LouisXO** [comment]
Issue Fixed with commit (Deleted show recommendations button)[Link](https://github.com/info442-spr22/h-team/tree/216d075396f389da786a9c55471db3e5f10d52a2)
