### ISSUE TITLE
(major)No recommendations are showing after finishing survey. 

### ISSUE THREAD

**Issue by victorgmaciel** [info442-spr22/h-team#47]
BUG

**Comment by victorgmaciel** [comment]
Clicking through the survey and filling out the options, at the end of the survey no recommendations are shown and the survey starts over.

**Comment by victorgmaciel** [comment]
OS: Windows 11 21H2, Chrome

**Comment by cherimarie** [comment]
For our purposes, this is a minor bug. It's a result of no user feedback when no matching islands are found. Recommendations are shown when certain form inputs are given, as demonstrated to me by the team. I still strongly recommend addressing this one.

**Comment by mariamk-2740** [comment]
Duplicate
