### ISSUE TITLE
(Minor) Recommended for you chopped off by footer on survey page (can't scroll to it)

### ISSUE THREAD

**Issue by cmarq07** [info442-spr22/h-team#48]
Chrome on Macbook Pro

**Comment by cmarq07** [comment]
Occurs possibly because there is not enough information on the specific page that causes the footer to be floated up from the bottom of the screen, causing it to truncate the form.

**Comment by mariamk-2740** [comment]
We will address this minor bug during this sprint.

**Comment by LouisXO** [comment]
Issue Fixed with commit[Link](https://github.com/info442-spr22/h-team/tree/216d075396f389da786a9c55471db3e5f10d52a2), (automatically shows the results instead of having show button)
