### ISSUE TITLE
(major bug) infinite loop of quiz questions

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/h-team#50]
After getting to the last question of the quiz, there is still a "next button", which takes me to the beginning of the quiz. This could cause a usability issue for first-time users who took the time to complete the quiz but didn't know what question was the last one and accidentally pressed next.
(encountered on chrome Version 101.0.4951.64)
To fix this, possibly remove the next button on the last question or put question numbers so the user knows their progress on the quiz.

**Comment by cherimarie** [comment]
For our purposes, this is a minor bug. It's a result of no user feedback when no matching islands are found. Recommendations are shown when certain form inputs are given, as demonstrated to me by the team. I still strongly recommend addressing this one.

**Comment by mariamk-2740** [comment]
Duplicate
