### ISSUE TITLE
(Minor bug) Home page is left-right scrollable

### ISSUE THREAD

**Issue by fretws** [info442-spr22/h-team#52]
The page is wider than my viewport, which I do not think is intentional.
Steps to recreate: Visit the home page
Expected result: The viewport width matching the rendered page width
Actual result: the page is wider than my viewport, making it horizontally scrollable
Windows 10, Chrome
This seems to happen on multiple viewport sizes, but I originally noticed it on 1538x829 (my natural resolution, not emulated)

**Comment by mariamk-2740** [comment]
Duplicate
