### ISSUE TITLE
(Major Bug) Survey loop

### ISSUE THREAD

**Issue by Jaehoon01** [info442-spr22/h-team#53]
When I complete the survey, no recommendations pop up and the survey starts again. Chrome on MacOS

**Comment by cherimarie** [comment]
For our purposes, this is a minor bug. It's a result of no user feedback when no matching islands are found. Recommendations are shown when certain form inputs are given, as demonstrated to me by the team. I still strongly recommend addressing this one.

**Comment by mariamk-2740** [comment]
Duplicate
