### ISSUE TITLE
Feature: Show recommendations appears after successful survey

### ISSUE THREAD

**Issue by cavazd** [info442-spr22/h-team#54]
* Description: Currently the Show Recommendations button and header for "Recommend for you" is always present. Instead of this, it becomes visible after finishing a survey.
* Explanation: It's a bit confusing having the button there early. I tried to click on it and nothing happened (a bug someone else has mentioned I think) but then I assumed I had to finish the survey first. Finishing the survey first and then getting recommendations makes the most sense in my opinion.

**Comment by mariamk-2740** [comment]
We see how this could help our site, but may not be able to address it in the time we have during this sprint

**Comment by mariamk-2740** [comment]
We can address this enhancement during the sprint.

**Comment by mariamk-2740** [comment]
We realized that this enhancement is a duplicate of [issue](https://github.com/info442-spr22/h-team/issues/46)
