### ISSUE TITLE
(Enhancement) Add a button to take the survey to the navigation bar

### ISSUE THREAD

**Issue by stroz08** [info442-spr22/h-team#56]
Having the survey also accessible by the nav bar would be nice for the user experience.

**Comment by mariamk-2740** [comment]
We see how this could help our site, but may not be able to address it in the time we have during this sprint

**Comment by LouisXO** [comment]
Issue Fixed with commit [Link](https://github.com/info442-spr22/h-team/commit/fc89aa808d0192f21fca7c81d5af6fffcd4b572d)
