### ISSUE TITLE
ENHANCEMENT: Show progress bar for survey

### ISSUE THREAD

**Issue by RachelChung2020** [info442-spr22/h-team#61]
Maybe have a progress bar at the bottom of the page for the survey because the survey felt kind of long towards the end, so having an idea of how long the survey is might be nice for users.

**Comment by mariamk-2740** [comment]
We see how this could help our site, but may not be able to address it in the time we have during this sprint

**Comment by LouisXO** [comment]
Issue Fixed with commit [Link](https://github.com/info442-spr22/h-team/commit/d734ee21772550545b61c324743f54d739d6dfe3)
