### ISSUE TITLE
(BUG, Major) No recommendations after submitting form

### ISSUE THREAD

**Issue by RachelChung2020** [info442-spr22/h-team#62]
After going through the survey, I do not get recommendations.

**Environment it was encountered in:** Chrome v101.0.4951.67 in Windows

Steps to reproduce:
1. Click "start survey" button
2. Fill out survey
3. Click complete button

**Expected result:** a page with recommendations

**Actual result:** goes back to the beginning of survey

**Comment by cherimarie** [comment]
For our purposes, this is a minor bug. It's a result of no user feedback when no matching islands are found. Recommendations are shown when certain form inputs are given, as demonstrated by the team. I still strongly recommend addressing this one.

**Comment by mariamk-2740** [comment]
Duplicate
