### ISSUE TITLE
Enhancement: Make the first page one chunk of text instead of two columns of text

### ISSUE THREAD

**Issue by abequette99** [info442-spr22/h-team#63]
Description: Currently you write out your problem info and description in two columns for the user they need to scroll down to finished one of the rows of text then scroll back up to read the other column. 

Explanation: By having one chunk of text not broken into two columns it make the information flow more and makes it easier for the user to stay engaged with the information. By taking away the columns it also means that the user does just read on column and skip over the other, they will most likely read to the end.

**Comment by mariamk-2740** [comment]
We see how this could help our site, but may not be able to address it in the time we have during this sprint

**Comment by LouisXO** [comment]
Issue Fixed with commit [Link](https://github.com/info442-spr22/h-team/commit/d734ee21772550545b61c324743f54d739d6dfe3), (Redesigned the home page)
