### ISSUE TITLE
Minor enhancement: spelling on survey

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/h-team#64]
just a heads up that there's a misspelled word on the survey, specifically the word "preference" on question 10

<img width="1277" alt="Screen Shot 2022-05-18 at 11 14 15 AM" src="https://user-images.githubusercontent.com/70997571/169116400-39907ed7-9402-4a71-850d-95d0a5406515.png">

**Comment by mariamk-2740** [comment]
Louis will make this small word spelling change.

**Comment by LouisXO** [comment]
Issue Fixed with commit [Link](https://github.com/info442-spr22/h-team/commit/d734ee21772550545b61c324743f54d739d6dfe3)
