### ISSUE TITLE
Minor Bug: Show Recommendations button cut off on smaller view

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/h-team#65]
When the window is minimized to the smallest view, the 'Show Recommendations' button becomes smaller, however, the text doesn't change sizes and gets cut off by the button.

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Steps to reproduce:

1. Click "take survey" on home page
2. Shrink window size to smallest

Expected result: "Show Recommendations" button fits the text and is readable 

Actual result: "Show Recommendations" is cut off by the button

<img width="205" alt="Screen Shot 2022-05-18 at 11 20 12 AM" src="https://user-images.githubusercontent.com/70997571/169117203-1339a67d-7cf6-4721-a55e-3578622462b6.png">

**Comment by mariamk-2740** [comment]
This is a valid point, but with the time that we have until the end of the sprint, we won't be able to address it.

**Comment by LouisXO** [comment]
Issue Fixed with commit  [Link](https://github.com/info442-spr22/h-team/commit/d734ee21772550545b61c324743f54d739d6dfe3) (Removed show button)
