### ISSUE TITLE
Minor bug: Unable to select "no preference" option

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/h-team#66]
When doing the survey, question 10 (the one about language) doesn't allow users to click on the "no preference option" first. It only works after selecting an option above and then switching to "no preference"

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Steps to reproduce

1. From home page, click 'start survey'
2. Take survey as usual until question 10
3. Click on the "no preference" option first

Expected result: Fills in circle upon click

Actual result: Doesn't fill in circle upon click

**Comment by mariamk-2740** [comment]
Louis will take care of this bug. We were able to recreate this bug and will fix it.

**Comment by LouisXO** [comment]
Issue Fixed with commit [Link](https://github.com/info442-spr22/h-team/commit/d734ee21772550545b61c324743f54d739d6dfe3), (Added guide for select the "no preference button")
