### ISSUE TITLE
Minor Bug: Links for names do not work in footer

### ISSUE THREAD

**Issue by alanytran** [info442-spr22/h-team#67]
It seems like it is supposed to be clickable because of how the name is lighter when you hover. However nothing is popping up for me. This seems like an easy fix by linking the names to another page or something
Chrome v90.0.4430.85 on macOS Monterey

**Comment by mariamk-2740** [comment]
We can't reproduce this bug. Clicking on the names in the footer prompts the mail application to open.

**Comment by mariamk-2740** [comment]
Asked the commenter, waiting for response
